### ISSUE TITLE
Edit Profile, Duplicate Fields

### ISSUE THREAD

**Issue by justinbesteman** [mainsite/selfstarted#108]
When an user click's update for their profile, it shows "Main User College"  and about me twice 

![self started - google chrome_010](https://cloud.githubusercontent.com/assets/19551504/24511047/e9d66580-1538-11e7-97f3-81eb914e895a.png)

**Comment by realzaidiguy** [comment]
I don't think that's a duplication. The first one shows what it's currently set to, while the second one allows you to change it. Unless I'm missing something?

**Comment by justinbesteman** [comment]
It is definitely a duplicate value if you look at the edit profile and you will see

**Comment by realzaidiguy** [comment]
Still not seeing it. Just looks like one current, and one edit, for the college/major. Same as the About Me and School Name.

**Comment by tachprime** [comment]
Updated with edit preface to make it more clear
