### ISSUE TITLE
Profile section bugs

### ISSUE THREAD

**Issue by realzaidiguy** [mainsite/selfstarted#146]
1) "Save Changes" button persists in the view mode of the profile. It should only be visible when in edit view.

2) After updating additional skills, they do not display in the profile. However, looking in Mongo, it looks like they are being correctly saved in the database.

3) Profile location is still showing the old deprecated "userLocation" from the database which was populated with linked in data. Instead it should show the newer userCountry, userState, userCity. Checking mongo, it does appear to correctly update, however, when you save those three fields.

**Comment by tachprime** [comment]
Should be working as intended now
