### ISSUE TITLE
User profile edit issue

### ISSUE THREAD

**Issue by realzaidiguy** [mainsite/selfstarted#160]
When editing user profile, if you enter in country/state/city to update, but leave the skills fields untouched, then when you submit it clears out your skills. Similarly, if you edit your profile and enter in new skills, but don't re-select your country/state/city, then when submit it forgets your location fields. Basically, the way it currently is, when editing profile you have to re-enter BOTH your country/city/state and your skills, if you try to update anything, or that data is lost.

**Comment by tachprime** [comment]
Should be all clear now. Wasn't as easy as I thought, needed to change a whole bunch of stuff to get the behavior right.  Just note that the once you touch Country you do have to re-enter state and city and there isn't much I can do about that.
